package com.icms.cms.model;

import com.icms.cms.model.base.BaseAd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ad extends BaseAd<Ad> {
    public static final Ad dao = new Ad();
}
