package com.icms.cms.model;

import com.icms.cms.model.base.BaseAdminRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminRole extends BaseAdminRole<AdminRole> {
    public static final AdminRole dao = new AdminRole();
}
