package com.icms.cms.model;

import com.icms.cms.model.base.BaseAdmin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Admin extends BaseAdmin<Admin> {
    public static final Admin dao = new Admin();
}
