package com.icms.cms.model;

import com.icms.cms.model.base.BaseArea;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Area extends BaseArea<Area> {
    public static final Area dao = new Area();
}
