package com.icms.cms.model;

import com.icms.cms.model.base.BaseCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Category extends BaseCategory<Category> {
    public static final Category dao = new Category();
}
