package com.icms.cms.model;

import com.icms.cms.model.base.BaseCommont;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Commont extends BaseCommont<Commont> {
    public static final Commont dao = new Commont();
}
