package com.icms.cms.model;

import com.icms.cms.model.base.BaseConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Config extends BaseConfig<Config> {
    public static final Config dao = new Config();
}
