package com.icms.cms.model;

import com.icms.cms.model.base.BaseConfigAttr;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ConfigAttr extends BaseConfigAttr<ConfigAttr> {
    public static final ConfigAttr dao = new ConfigAttr();
}
