package com.icms.cms.model;

import com.icms.cms.model.base.BaseContent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Content extends BaseContent<Content> {
    public static final Content dao = new Content();
}
