package com.icms.cms.model;

import com.icms.cms.model.base.BaseForm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Form extends BaseForm<Form> {
    public static final Form dao = new Form();
}
