package com.icms.cms.model;

import com.icms.cms.model.base.BaseLink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Link extends BaseLink<Link> {
    public static final Link dao = new Link();
}
