package com.icms.cms.model;

import com.icms.cms.model.base.BaseMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Member extends BaseMember<Member> {
    public static final Member dao = new Member();
}
