package com.icms.cms.model;

import com.icms.cms.model.base.BaseMemberGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberGroup extends BaseMemberGroup<MemberGroup> {
    public static final MemberGroup dao = new MemberGroup();
}
