package com.icms.cms.model;

import com.icms.cms.model.base.BaseMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Menu extends BaseMenu<Menu> {
    public static final Menu dao = new Menu();
}
