package com.icms.cms.model;

import com.icms.cms.model.base.BaseModelFiled;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ModelFiled extends BaseModelFiled<ModelFiled> {
    public static final ModelFiled dao = new ModelFiled();
}
