package com.icms.cms.model;

import com.icms.cms.model.base.BaseModel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Model extends BaseModel<Model> {
    public static final Model dao = new Model();
}
