package com.icms.cms.model;

import com.icms.cms.model.base.BasePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Permission extends BasePermission<Permission> {
    public static final Permission dao = new Permission();
}
