package com.icms.cms.model;

import com.icms.cms.model.base.BaseRolePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RolePermission extends BaseRolePermission<RolePermission> {
    public static final RolePermission dao = new RolePermission();
}
