package com.icms.cms.model;

import com.icms.cms.model.base.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
    public static final Role dao = new Role();
}
