package com.icms.cms.model;

import com.icms.cms.model.base.BaseSearchWords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SearchWords extends BaseSearchWords<SearchWords> {
    public static final SearchWords dao = new SearchWords();
}
