package com.icms.cms.model;

import com.icms.cms.model.base.BaseTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tag extends BaseTag<Tag> {
    public static final Tag dao = new Tag();
}
