package com.icms.cms.model;

import com.icms.cms.model.base.BaseTagContent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TagContent extends BaseTagContent<TagContent> {
    public static final TagContent dao = new TagContent();
}
