package com.icms.cms.model;

import com.icms.cms.model.base.BaseTaskContent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaskContent extends BaseTaskContent<TaskContent> {
    public static final TaskContent dao = new TaskContent();
}
