package com.icms.cms.model;

import com.icms.cms.model.base.BaseTopic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Topic extends BaseTopic<Topic> {
    public static final Topic dao = new Topic();
}
