package com.icms.cms.model;

import com.icms.cms.model.base.BaseWebsite;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Website extends BaseWebsite<Website> {
    public static final Website dao = new Website();
}
