package com.icms.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseContent<M extends BaseContent<M>> extends Model<M> implements IBean {

	public void setContentId(java.lang.Long contentId) {
		set("content_id", contentId);
	}

	public java.lang.Long getContentId() {
		return get("content_id");
	}

	public void setCategoryId(java.lang.Long categoryId) {
		set("category_id", categoryId);
	}

	public java.lang.Long getCategoryId() {
		return get("category_id");
	}

	public void setModelId(java.lang.Integer modelId) {
		set("model_id", modelId);
	}

	public java.lang.Integer getModelId() {
		return get("model_id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setKeywords(java.lang.String keywords) {
		set("keywords", keywords);
	}

	public java.lang.String getKeywords() {
		return get("keywords");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setTop(java.lang.Boolean top) {
		set("top", top);
	}

	public java.lang.Boolean getTop() {
		return get("top");
	}

	public void setRecommend(java.lang.Boolean recommend) {
		set("recommend", recommend);
	}

	public java.lang.Boolean getRecommend() {
		return get("recommend");
	}

	public void setThumb(java.lang.String thumb) {
		set("thumb", thumb);
	}

	public java.lang.String getThumb() {
		return get("thumb");
	}

	public void setStatus(java.lang.Boolean status) {
		set("status", status);
	}

	public java.lang.Boolean getStatus() {
		return get("status");
	}

	public void setInputdate(java.util.Date inputdate) {
		set("inputdate", inputdate);
	}

	public java.util.Date getInputdate() {
		return get("inputdate");
	}

	public void setUpdatedate(java.util.Date updatedate) {
		set("updatedate", updatedate);
	}

	public java.util.Date getUpdatedate() {
		return get("updatedate");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setUserId(java.lang.Integer userId) {
		set("user_id", userId);
	}

	public java.lang.Integer getUserId() {
		return get("user_id");
	}

	public void setIsDel(java.lang.Boolean isDel) {
		set("is_del", isDel);
	}

	public java.lang.Boolean getIsDel() {
		return get("is_del");
	}

	public void setViewNum(java.lang.Integer viewNum) {
		set("view_num", viewNum);
	}

	public java.lang.Integer getViewNum() {
		return get("view_num");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

}
