package com.icms.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseModel<M extends BaseModel<M>> extends Model<M> implements IBean {

	public void setModelId(java.lang.Integer modelId) {
		set("model_id", modelId);
	}

	public java.lang.Integer getModelId() {
		return get("model_id");
	}

	public void setModelName(java.lang.String modelName) {
		set("model_name", modelName);
	}

	public java.lang.String getModelName() {
		return get("model_name");
	}

	public void setTableName(java.lang.String tableName) {
		set("table_name", tableName);
	}

	public java.lang.String getTableName() {
		return get("table_name");
	}

	public void setFrontSubmit(java.lang.Boolean frontSubmit) {
		set("front_submit", frontSubmit);
	}

	public java.lang.Boolean getFrontSubmit() {
		return get("front_submit");
	}

	public void setAdminSubmit(java.lang.Boolean adminSubmit) {
		set("admin_submit", adminSubmit);
	}

	public java.lang.Boolean getAdminSubmit() {
		return get("admin_submit");
	}

	public void setSiteId(java.lang.Long siteId) {
		set("site_id", siteId);
	}

	public java.lang.Long getSiteId() {
		return get("site_id");
	}

	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}

	public java.lang.String getDesc() {
		return get("desc");
	}

	public void setStatus(java.lang.Boolean status) {
		set("status", status);
	}

	public java.lang.Boolean getStatus() {
		return get("status");
	}

	public void setIsContent(java.lang.Boolean isContent) {
		set("is_content", isContent);
	}

	public java.lang.Boolean getIsContent() {
		return get("is_content");
	}

}
