package com.icms.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMemberGroup<M extends BaseMemberGroup<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}

	public java.lang.Integer getId() {
		return get("Id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setNeedAudit(java.lang.Boolean needAudit) {
		set("need_audit", needAudit);
	}

	public java.lang.Boolean getNeedAudit() {
		return get("need_audit");
	}

	public void setNeedVerify(java.lang.Boolean needVerify) {
		set("need_verify", needVerify);
	}

	public java.lang.Boolean getNeedVerify() {
		return get("need_verify");
	}

}
