package com.icms.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseContentImages<M extends BaseContentImages<M>> extends Model<M> implements IBean {

	public void setContentId(java.lang.Long contentId) {
		set("content_id", contentId);
	}

	public java.lang.Long getContentId() {
		return get("content_id");
	}

	public void setData(java.lang.String data) {
		set("data", data);
	}

	public java.lang.String getData() {
		return get("data");
	}

}
