package com.icms.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCommont<M extends BaseCommont<M>> extends Model<M> implements IBean {

	public void setCommontId(java.lang.Integer commontId) {
		set("commont_id", commontId);
	}

	public java.lang.Integer getCommontId() {
		return get("commont_id");
	}

	public void setArticleId(java.lang.Long articleId) {
		set("article_id", articleId);
	}

	public java.lang.Long getArticleId() {
		return get("article_id");
	}

	public void setReplyId(java.lang.Integer replyId) {
		set("reply_id", replyId);
	}

	public java.lang.Integer getReplyId() {
		return get("reply_id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setPostDate(java.util.Date postDate) {
		set("post_date", postDate);
	}

	public java.util.Date getPostDate() {
		return get("post_date");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

}
