package com.icms.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseModelFiled<M extends BaseModelFiled<M>> extends Model<M> implements IBean {

	public void setFiledId(java.lang.Integer filedId) {
		set("filed_id", filedId);
	}

	public java.lang.Integer getFiledId() {
		return get("filed_id");
	}

	public void setModelId(java.lang.Integer modelId) {
		set("model_id", modelId);
	}

	public java.lang.Integer getModelId() {
		return get("model_id");
	}

	public void setFiledName(java.lang.String filedName) {
		set("filed_name", filedName);
	}

	public java.lang.String getFiledName() {
		return get("filed_name");
	}

	public void setFiledClass(java.lang.String filedClass) {
		set("filed_class", filedClass);
	}

	public java.lang.String getFiledClass() {
		return get("filed_class");
	}

	public void setFiledValue(java.lang.String filedValue) {
		set("filed_value", filedValue);
	}

	public java.lang.String getFiledValue() {
		return get("filed_value");
	}

	public void setFiledType(java.lang.String filedType) {
		set("filed_type", filedType);
	}

	public java.lang.String getFiledType() {
		return get("filed_type");
	}

	public void setAlias(java.lang.String alias) {
		set("alias", alias);
	}

	public java.lang.String getAlias() {
		return get("alias");
	}

	public void setNotNull(java.lang.Boolean notNull) {
		set("not_null", notNull);
	}

	public java.lang.Boolean getNotNull() {
		return get("not_null");
	}

	public void setFiledLength(java.lang.Integer filedLength) {
		set("filed_length", filedLength);
	}

	public java.lang.Integer getFiledLength() {
		return get("filed_length");
	}

}
