package com.icms.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdmin<M extends BaseAdmin<M>> extends Model<M> implements IBean {

	public void setAdminId(java.lang.Integer adminId) {
		set("admin_id", adminId);
	}

	public java.lang.Integer getAdminId() {
		return get("admin_id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setSalt(java.lang.String salt) {
		set("salt", salt);
	}

	public java.lang.String getSalt() {
		return get("salt");
	}

	public void setLastip(java.lang.String lastip) {
		set("lastip", lastip);
	}

	public java.lang.String getLastip() {
		return get("lastip");
	}

	public void setLastdate(java.util.Date lastdate) {
		set("lastdate", lastdate);
	}

	public java.util.Date getLastdate() {
		return get("lastdate");
	}

	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}

	public java.util.Date getCreatedate() {
		return get("createdate");
	}

	public void setSiteId(java.lang.Integer siteId) {
		set("site_id", siteId);
	}

	public java.lang.Integer getSiteId() {
		return get("site_id");
	}

	public void setLoginsum(java.lang.Integer loginsum) {
		set("loginsum", loginsum);
	}

	public java.lang.Integer getLoginsum() {
		return get("loginsum");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setStatus(java.lang.Boolean status) {
		set("status", status);
	}

	public java.lang.Boolean getStatus() {
		return get("status");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

}
