package com.icms.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseForm<M extends BaseForm<M>> extends Model<M> implements IBean {

	public void setFormId(java.lang.Integer formId) {
		set("form_id", formId);
	}

	public java.lang.Integer getFormId() {
		return get("form_id");
	}

	public void setModelId(java.lang.Integer modelId) {
		set("model_id", modelId);
	}

	public java.lang.Integer getModelId() {
		return get("model_id");
	}

	public void setActionkey(java.lang.String actionkey) {
		set("actionkey", actionkey);
	}

	public java.lang.String getActionkey() {
		return get("actionkey");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setIsAuth(java.lang.Boolean isAuth) {
		set("is_auth", isAuth);
	}

	public java.lang.Boolean getIsAuth() {
		return get("is_auth");
	}

}
