package com.icms.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTopic<M extends BaseTopic<M>> extends Model<M> implements IBean {

	public void setTopicId(java.lang.Integer topicId) {
		set("topic_id", topicId);
	}

	public java.lang.Integer getTopicId() {
		return get("topic_id");
	}

	public void setCategoryIds(java.lang.String categoryIds) {
		set("category_ids", categoryIds);
	}

	public java.lang.String getCategoryIds() {
		return get("category_ids");
	}

	public void setTopicName(java.lang.String topicName) {
		set("topic_name", topicName);
	}

	public java.lang.String getTopicName() {
		return get("topic_name");
	}

	public void setShortName(java.lang.String shortName) {
		set("short_name", shortName);
	}

	public java.lang.String getShortName() {
		return get("short_name");
	}

	public void setKeywords(java.lang.String keywords) {
		set("keywords", keywords);
	}

	public java.lang.String getKeywords() {
		return get("keywords");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setTitleImg(java.lang.String titleImg) {
		set("title_img", titleImg);
	}

	public java.lang.String getTitleImg() {
		return get("title_img");
	}

	public void setContentImg(java.lang.String contentImg) {
		set("content_img", contentImg);
	}

	public java.lang.String getContentImg() {
		return get("content_img");
	}

	public void setTplContent(java.lang.String tplContent) {
		set("tpl_content", tplContent);
	}

	public java.lang.String getTplContent() {
		return get("tpl_content");
	}

	public void setPriority(java.lang.Integer priority) {
		set("priority", priority);
	}

	public java.lang.Integer getPriority() {
		return get("priority");
	}

	public void setIsRecommend(java.lang.Boolean isRecommend) {
		set("is_recommend", isRecommend);
	}

	public java.lang.Boolean getIsRecommend() {
		return get("is_recommend");
	}

}
