package com.icms.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFormForm<M extends BaseFormForm<M>> extends Model<M> implements IBean {

	public void setFormId(java.lang.Integer formId) {
		set("form_id", formId);
	}

	public java.lang.Integer getFormId() {
		return get("form_id");
	}

	public void setContents(java.lang.String contents) {
		set("contents", contents);
	}

	public java.lang.String getContents() {
		return get("contents");
	}

}
