package com.icms.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCategory<M extends BaseCategory<M>> extends Model<M> implements IBean {

	public void setCategoryId(java.lang.Long categoryId) {
		set("category_id", categoryId);
	}

	public java.lang.Long getCategoryId() {
		return get("category_id");
	}

	public void setShortname(java.lang.String shortname) {
		set("shortname", shortname);
	}

	public java.lang.String getShortname() {
		return get("shortname");
	}

	public void setCategoryName(java.lang.String categoryName) {
		set("category_name", categoryName);
	}

	public java.lang.String getCategoryName() {
		return get("category_name");
	}

	public void setSiteId(java.lang.Integer siteId) {
		set("site_id", siteId);
	}

	public java.lang.Integer getSiteId() {
		return get("site_id");
	}

	public void setParentId(java.lang.Long parentId) {
		set("parent_id", parentId);
	}

	public java.lang.Long getParentId() {
		return get("parent_id");
	}

	public void setModelId(java.lang.Integer modelId) {
		set("model_id", modelId);
	}

	public java.lang.Integer getModelId() {
		return get("model_id");
	}

	public void setAlone(java.lang.Boolean alone) {
		set("alone", alone);
	}

	public java.lang.Boolean getAlone() {
		return get("alone");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setIndexTpl(java.lang.String indexTpl) {
		set("index_tpl", indexTpl);
	}

	public java.lang.String getIndexTpl() {
		return get("index_tpl");
	}

	public void setListTpl(java.lang.String listTpl) {
		set("list_tpl", listTpl);
	}

	public java.lang.String getListTpl() {
		return get("list_tpl");
	}

	public void setContentTpl(java.lang.String contentTpl) {
		set("content_tpl", contentTpl);
	}

	public java.lang.String getContentTpl() {
		return get("content_tpl");
	}

	public void setIsNav(java.lang.Boolean isNav) {
		set("is_nav", isNav);
	}

	public java.lang.Boolean getIsNav() {
		return get("is_nav");
	}

	public void setAllowFrontPost(java.lang.Boolean allowFrontPost) {
		set("allow_front_post", allowFrontPost);
	}

	public java.lang.Boolean getAllowFrontPost() {
		return get("allow_front_post");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

}
