package com.icms.cms.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTag<M extends BaseTag<M>> extends Model<M> implements IBean {

	public void setTagId(java.lang.Integer tagId) {
		set("tag_id", tagId);
	}

	public java.lang.Integer getTagId() {
		return get("tag_id");
	}

	public void setTagName(java.lang.String tagName) {
		set("tag_name", tagName);
	}

	public java.lang.String getTagName() {
		return get("tag_name");
	}

	public void setLetter(java.lang.String letter) {
		set("letter", letter);
	}

	public java.lang.String getLetter() {
		return get("letter");
	}

	public void setCount(java.lang.Integer count) {
		set("count", count);
	}

	public java.lang.Integer getCount() {
		return get("count");
	}

}
